theme = "soho"
baseurl = "https://kiarashazarnia.github.io/"
# disqusShortname = "kiarashazarnia"
googleAnalytics = "G-PBK56M9G9N"
languageCode = "en"
title = "Kiarash Azarnia"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "Kiarash Azarnia"
description = "Software Engineer"
# gravatar = "soho@example.com"
images = ["images/profile.png"]
profilePicture = "images/me_square.jpg"
copyright = "Kiarash Azarnia"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
themeColor = "#0F52BA"
## blue "#0E6655"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/kiarashazarnia/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/kiarashazarnia"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/kiarashazarnia"

  [[params.socialIcons]]
  icon = "fa-instagram"
  title = "Instagram"
  url = "https://www.instagram.com/kiarashazarnia/"

  [[params.socialIcons]]
  icon = "fa-medium"
  title = "Medium"
  url = "https://medium.com/@kiarashazarnia"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
